### ISSUE TITLE
Cannot clone this repo

### ISSUE THREAD

**Issue by ritzmann** [walles/homebrew-johan#7]
Very strange, any idea what is going wrong here:
```shell
$ git clone https://github.com/walles/homebrew-johan.git
Cloning into 'homebrew-johan'...
remote: Enumerating objects: 972142, done.
remote: Counting objects: 100% (527/527), done.
remote: Compressing objects: 100% (245/245), done.
remote: Total 972142 (delta 322), reused 471 (delta 282), pack-reused 971615
Receiving objects: 100% (972142/972142), 388.01 MiB | 953.00 KiB/s, done.
Resolving deltas: 100% (662492/662492), done.
fatal: multiple updates for ref 'refs/remotes/origin/master' not allowed
```

```shell
$ git --version
git version 2.24.3 (Apple Git-128)
```

388.01 MB does not look right.

**Comment by ritzmann** [comment]
Just got the same issue when trying to clone my homebrew-core fork, so I guess you had forked homebrew-core and then removed everything in the end to create this repo? Anyway, the issue seems to be caused by homebrew-core, your clone just inherited the problem.

**Comment by walles** [comment]
Works for me, see below. Partly in Swedish, but still.

Agree that 381MiB sounds like a lot, I get 11KiB when I try your command line.

Two things:
1. I'm using Homebrew `git` (try `brew install git`)
2. My main branch is called `main`,  not `master`, which is mentioned in your error message.

It kind of looks like you're cloning something else, but the command line looks right so I'm confused.

```sh
/t/hej $ git clone https://github.com/walles/homebrew-johan.git
Klonar till "homebrew-johan"...
remote: Enumerating objects: 72, done.
remote: Counting objects: 100% (72/72), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 72 (delta 15), reused 66 (delta 12), pack-reused 0
Tar emot objekt: 100% (72/72), 11,39 KiB | 777,00 KiB/s, klart.
Analyserar delta: 100% (15/15), klart.
/t/hej $ git --version
git version 2.31.1
```

**Comment by ritzmann** [comment]
I had copied my Git client config from another account and picked up some harmful settings. Fixed now, was a misconfiguration on my side:
https://stackoverflow.com/questions/54922704/git-cloning-error-fatal-multiple-updates-for-ref-not-allowed
